read_file -format verilog ../../module/riscv_core/rtl_v00/imm_gen.v
read_file -format verilog ../../module/riscv_core/rtl_v00/alu_ctrl.v
read_file -format verilog ../../module/riscv_core/rtl_v00/foward_unit.v
read_file -format verilog ../../module/riscv_core/rtl_v00/hazard_detec.v
read_file -format verilog ../../module/riscv_core/rtl_v00/alu_ex.v
read_file -format verilog ../../module/riscv_core/rtl_v00/alu_add.v
read_file -format verilog ../../module/riscv_core/rtl_v00/regfile.v
read_file -format verilog ../../module/riscv_core/rtl_v00/mem_wb.v
read_file -format verilog ../../module/riscv_core/rtl_v00/if_id.v
read_file -format verilog ../../module/riscv_core/rtl_v00/main_ctrl.v
read_file -format verilog ../../module/riscv_core/rtl_v00/ex_mem.v
read_file -format verilog ../../module/riscv_core/rtl_v00/id_ex.v
read_file -format verilog ../../module/riscv_core/rtl_v00/mux2.v
read_file -format verilog ../../module/riscv_core/rtl_v00/mux3.v
read_file -format verilog ../../module/riscv_core/rtl_v00/riscv_core.v
read_file -format verilog ../../module/wrap/rtl_v00/wrap_dram.v
read_file -format verilog ../../module/wrap/rtl_v00/wrap_iram.v
read_file -format verilog ../../module/chip/rtl_v00/CHIP_TOP.v
